# install systeme


ufapp1_perl_pkgs = value_for_platform(
  ['debian', 'ubuntu'] => {
    'default' => [ 'libcgi-application-basic-plugin-bundle-perl','libcgi-application-extra-plugin-bundle-perl','libauthen-sasl-perl','libauthen-simple-net-perl','libdbd-mysql-perl','libpg-perl','libredis-perl','libclass-date-perl','libconfig-json-perl','libdata-format-html-perl','libdata-sorting-perl','libdata-treedumper-perl','libdatetime-format-builder-perl','libencode-perl','libconvert-ascii-armour-perl','libcrypt-ciphersaber-perl','libcrypt-dsa-perl','libcrypt-openssl-dsa-perl','libcrypt-openssl-rsa-perl','libcrypt-passwdmd5-perl','libcrypt-simple-perl','libtie-encryptedhash-perl','libdigest-crc-perl','libdigest-hmac-perl','libdigest-jhash-perl','libdigest-md5-file-perl','libdigest-md2-perl','libdigest-md4-perl','libdigest-md5-file-perl','libdigest-perl','libdigest-sha-perl','libemail-mime-contenttype-perl','libemail-mime-createhtml-perl','libemail-mime-encodings-perl','libemail-mime-perl','libemail-sender-perl','libemail-sender-transport-smtp-tls-perl','libmail-sender-perl','liblwp-protocol-https-perl','libnet-proxy-perl','libnet-sftp-foreign-perl','libnet-smtp-ssl-perl','libnet-smtp-tls-perl','libnet-smtpauth-perl','libnet-ssh-perl','libnet-ssh2-perl','libfile-fcntllock-perl','libwww-curl-perl','libwww-perl','libhtml-html5-entities-perl','libhtml-mason-perl','libtext-glob-perl','libtext-iconv-perl','liburi-encode-perl','libxml-xslt-perl','libcache-memcached-fast-perl','libcache-memcached-managed-perl','libcache-memcached-perl','libmemcached-tools','libcgi-session-driver-memcached-perl','libcgi-session-expiresessions-perl','libcgi-session-perl','libcgi-session-serialize-yaml-perl']
  },
  ['centos', 'redhat', 'fedora', 'amazon'] => {
    'default' => [ 'libcgi-application-basic-plugin-bundle-perl','libcgi-application-extra-plugin-bundle-perl','libauthen-sasl-perl','libauthen-simple-net-perl','libdbd-mysql-perl','libpg-perl','libredis-perl','libclass-date-perl','libconfig-json-perl','libdata-format-html-perl','libdata-sorting-perl','libdata-treedumper-perl','libdatetime-format-builder-perl','libencode-perl','libconvert-ascii-armour-perl','libcrypt-ciphersaber-perl','libcrypt-dsa-perl','libcrypt-openssl-dsa-perl','libcrypt-openssl-rsa-perl','libcrypt-passwdmd5-perl','libcrypt-simple-perl','libtie-encryptedhash-perl','libdigest-crc-perl','libdigest-hmac-perl','libdigest-jhash-perl','libdigest-md5-file-perl','libdigest-md2-perl','libdigest-md4-perl','libdigest-md5-file-perl','libdigest-perl','libdigest-sha-perl','libemail-mime-contenttype-perl','libemail-mime-createhtml-perl','libemail-mime-encodings-perl','libemail-mime-perl','libemail-sender-perl','libemail-sender-transport-smtp-tls-perl','libmail-sender-perl','liblwp-protocol-https-perl','libnet-proxy-perl','libnet-sftp-foreign-perl','libnet-smtp-ssl-perl','libnet-smtp-tls-perl','libnet-smtpauth-perl','libnet-ssh-perl','libnet-ssh2-perl','libfile-fcntllock-perl','libwww-curl-perl','libwww-perl','libhtml-html5-entities-perl','libhtml-mason-perl','libtext-glob-perl','libtext-iconv-perl','liburi-encode-perl','libxml-xslt-perl','libcache-memcached-fast-perl','libcache-memcached-managed-perl','libcache-memcached-perl','libmemcached-tools','libcgi-session-driver-memcached-perl','libcgi-session-expiresessions-perl','libcgi-session-perl','libcgi-session-serialize-yaml-perl']
  },
  'default' => ['libcgi-application-basic-plugin-bundle-perl','libcgi-application-extra-plugin-bundle-perl','libauthen-sasl-perl','libauthen-simple-net-perl','libdbd-mysql-perl','libpg-perl','libredis-perl','libclass-date-perl','libconfig-json-perl','libdata-format-html-perl','libdata-sorting-perl','libdata-treedumper-perl','libdatetime-format-builder-perl','libencode-perl','libconvert-ascii-armour-perl','libcrypt-ciphersaber-perl','libcrypt-dsa-perl','libcrypt-openssl-dsa-perl','libcrypt-openssl-rsa-perl','libcrypt-passwdmd5-perl','libcrypt-simple-perl','libtie-encryptedhash-perl','libdigest-crc-perl','libdigest-hmac-perl','libdigest-jhash-perl','libdigest-md5-file-perl','libdigest-md2-perl','libdigest-md4-perl','libdigest-md5-file-perl','libdigest-perl','libdigest-sha-perl','libemail-mime-contenttype-perl','libemail-mime-createhtml-perl','libemail-mime-encodings-perl','libemail-mime-perl','libemail-sender-perl','libemail-sender-transport-smtp-tls-perl','libmail-sender-perl','liblwp-protocol-https-perl','libnet-proxy-perl','libnet-sftp-foreign-perl','libnet-smtp-ssl-perl','libnet-smtp-tls-perl','libnet-smtpauth-perl','libnet-ssh-perl','libnet-ssh2-perl','libfile-fcntllock-perl','libwww-curl-perl','libwww-perl','libhtml-html5-entities-perl','libhtml-mason-perl','libtext-glob-perl','libtext-iconv-perl','liburi-encode-perl','libxml-xslt-perl','libcache-memcached-fast-perl','libcache-memcached-managed-perl','libcache-memcached-perl','libmemcached-tools','libcgi-session-driver-memcached-perl','libcgi-session-expiresessions-perl','libcgi-session-perl','libcgi-session-serialize-yaml-perl']
)

ufapp1_perl_pkgs.each do |pkg|
  package pkg do
    action :install
  end
end

